### ISSUE TITLE
Only send client list on connection/disconnection

### ISSUE THREAD

**Issue by AdamRolek500** [ajchili/sync#106]

**Comment by ajchili** [comment]
This will have to be done after #102 due to a bug that will kick clients when another client leaves the server. This bug only occurs with the suggested change, I am currently not able to fully dive into why it happens but it only occurs when the client list is sent on client connection/disconnection.

**Comment by ajchili** [comment]
This won't be possible as client information is required to be sent continuously to connected clients.
